### ISSUE TITLE
Write Documentation

### ISSUE THREAD

**Issue by Guilhermeslucas** [CSELATAM/LUIS-Samples#1]
Documentation needed in order to help other engineers on [this file](https://github.com/CSELATAM/LUIS-Samples/blob/master/documentation-samples/authoring-api-samples/python/luis-app.py).

**Comment by Guilhermeslucas** [comment]
Just finished the documentation! @allantargino and @GeisaFaustino , since you're the ones whom will use this code, can you please take a look at it and see if the documentation makes sense for you? 
Thanks a lot!

**Comment by allantargino** [comment]
LGTM, great!!
